# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-11 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['city', 'zip']},
        ),
        migrations.AlterField(
            model_name='place',
            name='type',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
