# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-11 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_auto_20180311_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='location_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
