# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-12 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_auto_20180311_0154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['county', 'zip']},
        ),
        migrations.AlterField(
            model_name='place',
            name='county',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
