# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-18 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_auto_20180312_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
